{% set version = "1.3.6" %}

package:
  name: odfpy
  version: {{ version }}

source:
  fn: odfpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/odfpy/odfpy-{{ version }}.tar.gz
  sha256: 6bcaf3b23aa9e49ed8c8c177266539b211add4e02402748a994451482a10cb1b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - odf

about:
  home: https://github.com/eea/odfpy
  license: Apache-2.0
  license_file: APACHE-LICENSE-2.0.txt
  summary: 'Python API and tools to manipulate OpenDocument files.'

extra:
  recipe-maintainers:
    - ocefpaf
