{% set version = "1.4.0" %}

package:
  name: odfpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/odfpy/odfpy-{{ version }}.tar.gz
  sha256: 596021f0519623ca8717331951c95e3b8d7b21e86edc7efe8cb650a0d0f59a2b

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - defusedxml

test:
  imports:
    - odf

about:
  home: https://github.com/eea/odfpy
  license: Apache-2.0
  license_file: APACHE-LICENSE-2.0.txt
  summary: 'Python API and tools to manipulate OpenDocument files'

extra:
  recipe-maintainers:
    - ocefpaf
