travis:
  secure:
    BINSTAR_TOKEN: l+R6xPtbyZS04DBZqFJCLaXQrIHEh3naS4Zu4PqBU84+T458eb7pxuDme+7MQIIELGhNMsyoAssPdQn6fT0SydCeGnXOujjz854Z32R5H9W54PoyV6yFyGnHSQ8X7V4PdBKF1ZcGSZez8Nr5h9ABTped8Aw7uOmvUKJBPpunqoVmdkaEFvUIEGLDcNZEMOtyj1FScECK90hEBNzmf4Rbh18ngGbUv/Sfnkhs3obhzNc6tvT381MjJkBkpO2fU/oxJYVL6Mftt2sUzAMep0IK2qUU2dGcOkV4JaARLNyI8wfb9uoDn7wCQabQYTmHXq5Hr9FvrolS+3r+eaTfnVXmoXbfreB3EhPQDFivKNMRs4hTa58ioJlPom2Ee8jbo064ZORipIVn+r+e3yLr0AArVSu23pGk/iKcRZ8FHd5tTa3GdFmrUYQPjzziaEq4vCx32N5uGTAPA0vlSWZzxGK1tTlmF6z643ZHFmKEh7+m+Rngx6H2qWsscaYWCmWJV8ubNE42ZcA31pv4IKo4KWRwEp6HzUDraSf0dKBBs3D55cJEFFlNxumFYPej9x5reKSgRzuSFispOYeN3UCyAHCnGFKqaC8ZRxnHtLNTzI3XhIRdeDU50iAPaT9fJNGJ86LEwbRbeDEbvGy09S9I4Tplyu63aGSqNgKrWOxV+Mz1DrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
