travis:
  secure:
    BINSTAR_TOKEN: trhsG08XktBxVJEyokU0HHR09F4Jt92FfxWOp9FHCFNYoAz2b0ZCbQT7nNhjTrzDxcMXwAxJuc4XEU/994NO6UwiGPT++zehKmZoolST4b7upc5NTfSEgQIqfo3PEfPv4gUM4TmXvobG7dzsmP0u2xZjFhJ5AFqdpbhl6brP+Mi6gMbhjK6Gdk4NemBjxhyl7175l7zAhqoWnNftqBRG53acHivl6EOqpGTivh1Bk9DvTsQhjLU5Veg9CxV3XC7vbs827uZBWfsOGOBD2vjrRW6LqLtKLwSUxuyO087v+x5WtleDneyDKmQZzSlo8OOQjZ4ZMQ5r/vTB/qOeRXsXuUwe9UlAiEO+PRx4lvK4ZiUYr8WBvsSCgC2VL0o8CMU7dUAbPYPesKU9sKmALqDBiMEn28hqKC0CyOGq4Gb0ZhCnqW6W88A+QSglcBZqeGLdva8raOT+MSLxGT3bCsQERZ5Zi6Z0zvPYnajksA9dIxQzRe+kAHeqktmUjk8+x8MJWipMSFVMoWw+e07BziAr9ryryqX9tXu2ez914H0qh3bA/kRRtTmdwhdfepsXC/4Lzpvix1I2pZ+uA5qgZLh9165gqo19A20C24GmMbhZ/YyeZm+E/+FLjiQpy6z4PG8DZbWzMK7qD9Sa7nQJ86uv1URLFj0+rsm7ygy1eRjYFf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
