travis:
  secure:
    BINSTAR_TOKEN: tqAMNxsLaDXs0pVRB1JLH2EPZXRXabRJqrM6sIYeUDOW8fZb6ctrqar/W7j2P9yiHdGQuz/8//fP1DWsjGSt8/JacUtAhMYaDKcbLfQvpni3VJr6EdGyRmQsyiPoCYQ2kuHliJTsHfU0QTYedCayPdVWRT2ius/dw0Dx9T8Kv21uFxbSEKouzPsCgAaIoh+1yHFPrECnJ6VmigqwH6rkJ2P2riDWz+YMRU0Odj2oRe+AP8HWcRhu3X6BZT7/DYtbXldYPXKVYjvPm0g/9jEWrLuZOW0QooaObeM/ArAjj5S9iwVBGFUYLYMYU4VPwQCb7wNwewObFy11Q9j7rFc02u65R30HtESXuwQav6zAjm+IqCTrE62MmJ7btvkgZx5jQ6VADvfs4lg1NNyE/qRgwsmI3gKOdJyuIFKJI06QO7I0EndNydGmPLrkaHgVird5EtdCyaHCWsZwHAncKg0V9keI44vILmIb9kLdMhteYY+mMQpa3JFCN3vyrlJ1B9QPgl4xOHGDMXISKrs1dkQn4QSCYfCkDmZDx5FWUGGmeoNUlYFvklF0bMtDpRkAh0tqcB3BtEhsTt9TddiMqW9OEg1pauyvtRZRX2qbnBRaEP0RuZ8DfILsDk+GEzZvZGKXZUuXZy9tASMKpAVU0rq/CrCtlyS7+Xq1d6+wxAXVNic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
